spring.application.name=project
project.version = 1.0.0
spring.datasource.driver-class-name=org.h2.Driver
application.recommendations-db.url=jdbc:h2:file:./transaction
spring.datasource.url=jdbc:h2:mem://team_work
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate
telegram.bot.name=Money_Perspective_Bot
telegram.bot.token=7736367045:AAHZnoxhk26xZ-kJ3GZjBVB_PFn3JZEVXi0
